stages:
  - install
  - build
  - deploy
  - notifications

.cache: &npm_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
  policy: pull

install:
  image: node
  stage: install
  script: yarn
  cache:
    <<: *npm_cache
    policy: push
  only:
    changes:
      - yarn.lock

build:
  image: node
  stage: build
  script: yarn build
  cache: *npm_cache
  artifacts:
    paths:
      - dist
    expire_in: 1 hr

deploy:
  image: docker
  stage: deploy
  script: echo "I'm successfully deployed!"
  cache: {}

notify:
  image: alpine
  stage: post_deploy
  cache: {}
  dependencies: []
  script: echo "Notification is sent"
