# Reference: https://docs.gitlab.com/ee/ci/yaml/#environmentname
# dynamic environments: https://docs.gitlab.com/ee/ci/yaml/#dynamic-environments
# documentation: https://docs.gitlab.com/ee/ci/environments.html
# retrying and rolling back: https://docs.gitlab.com/ee/ci/environments.html#retrying-and-rolling-back
# review apps: https://docs.gitlab.com/ee/ci/review_apps

stages:
  - deploy

.deploy_shared:
  image: $DOCKER_REPO/mcmakler-deploy:latest
  dependencies: []
  before_script:
    - entrypoint.sh
  script:
    - deploy-app --namespace $K8S_NAMESPACE $APPNAME-$CI_COMMIT_REF_SLUG

deploy_review:
  extends: .deploy_shared
  stage: deploy
  variables:
    K8S_NAMESPACE: develop
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://$APPNAME-$CI_COMMIT_REF_SLUG.mcmakler.com
    on_stop: stop_review_app
    auto_stop_in: 1 week
  only:
    - branches
  except:
    - master
    - develop

deploy_develop:
  extends: .deploy_shared
  stage: deploy
  environment:
    name: development
    url: https://$APPNAME-$CI_COMMIT_REF_SLUG.mcmakler.com
  variables:
    K8S_NAMESPACE: develop
  only:
    - develop

deploy_prod:
  extends: .deploy_shared
  stage: deploy
  environment:
    name: production
    url: https://mein.mcmakler.de
  variables:
    K8S_NAMESPACE: production
  only:
    - master
  tags:
    - production

stop_review_app:
  stage: deploy
  image: $DOCKER_REPO/mcmakler-deploy:latest
  environment:
    name: review/$CI_COMMIT_REF_SLUG # name of environment
    action: stop # stop action
  variables:
    GIT_STRATEGY: none # don't need repo
  when: manual # this is important as we want to trigger this job only when env is stopped
  cache: {}
  dependencies: []
  script:
    - |
      kubectl delete \
        --namespace develop \ # deployment.yml#metadata.namespace
        $APPNAME-$CI_COMMIT_REF_SLUG # deployment.yml#metadata.name
    - |
      kubectl delete hpa \
        --namespace develop \  # HorizontalPodAutoscaler.yml#metadata.namespace
        $APPNAME-$CI_COMMIT_REF_SLUG # HorizontalPodAutoscaler.yml#metadata.name
  except: # never run on develop, staging and master
    - develop
    - staging
    - master
